---
- name: Gather OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install required packages on {{ ansible_distribution }}
  package:
    name: "{{ containerd_packages }}"
    state: latest

- name: Get Containerd
  unarchive:
    src: "{{ containerd_fetch_uri | default('https://github.com/containerd/containerd/releases/download/v' + containerd.release_version + '/containerd-' + containerd.release_version + '.linux-amd64.tar.gz') }}"
    dest: "/"
    remote_src: yes

- name: Create a directory for containerd config
  file:
    path: /etc/containerd
    state: directory

- name: Add containerd config file
  blockinfile:
    path: /etc/containerd/config.toml
    create: yes
    block: |
      [plugins.cri]
         enable_tls_streaming = true

- name: Copy containerd systemd unit file
  copy:
    src: containerd.service
    dest: /lib/systemd/system

- name: Start containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    state: started
    enabled: yes
